### ISSUE TITLE
Initialize_from_config

### ISSUE THREAD

**Issue by liangmuxin** [usc-isi-i2/dsbox-ta2#101]
``I have no name!@38d2366a083b:/muxin/dsbox-ta2/python$ python3 ta2-search /muxin/confs/conf_38sick.json
Namespace(configuration_file='/muxin/confs/conf_38sick.json', cpus=-1, debug=False, output_prefix=None, timeout=-1)
Using configuation:
{'cpus': '10',
 'dataset_schema': '/muxin/data/38_sick/TRAIN/dataset_TRAIN/datasetDoc.json',
 'executables_root': '/muxin/results',
 'pipeline_logs_root': '/muxin/results',
 'problem_root': '/muxin/data/38_sick/TRAIN/problem_TRAIN',
 'problem_schema': '/muxin/data/38_sick/TRAIN/problem_TRAIN/problemDoc.json',
 'ram': '10Gi',
 'saved_pipeline_ID': '',
 'saving_folder_loc': '/muxin/results',
 'temp_storage_root': '/muxin/results',
 'test_data_schema': '/muxin/data/38_sick/TRAIN/dataset_TRAIN/datasetDoc.json',
 'timeout': 499,
 'train_data_schema': '/muxin/data/38_sick/TRAIN/dataset_TRAIN/datasetDoc.json',
 'training_data_root': '/muxin/data/38_sick/TRAIN/dataset_TRAIN'}
[INFO] Test data config found! Will use given test data.
Traceback (most recent call last):
  File "ta2-search", line 141, in <module>
    result = main(args)
  File "ta2-search", line 105, in main
    controller.initialize_from_config(config)
AttributeError: 'Controller' object has no attribute 'initialize_from_config'
I have no name!@38d2366a083b:/muxin/dsbox-ta2/python$

This error happens from the latest version from temp-2018-june when I put in previous config files. 
Maybe we should union the way of writing a config file and remove that part from ta2-search? I guess there are some contents in config that are never called and I was also told that there will be no testing dataset in config anymore.

**Comment by ckxz105** [comment]
Do not give 'test_data_schema' in config, otherwise the function will try to use this method but this method should not be called
