### ISSUE TITLE
Denormalize primitive in common primitives

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#102]
The Denormalize primitive has been added back into the common primitives 

https://gitlab.com/datadrivendiscovery/common-primitives/blob/master/entry_points.ini#L39

We should look into using it. Looks like its building the denormalize dataframe more efficiently, and it has some additional logic to handle graph data.

**Comment by RqS** [comment]
Use our own, since common_primitives.denormalize works slow
