### ISSUE TITLE
SKLinearSVC take long time and lot of memories

### ISSUE THREAD

**Issue by ckxz105** [usc-isi-i2/dsbox-ta2#103]
When testing on the dataset (e.g. No.38), it seems "d3m.primitives.sklearn_wrap.SKLinearSVC" primitive will cost a very very long time to fit the model and produce the results. This error is especially serious if ran on local environment.
This primitive exist in "classifier_model" function in library.py and will be called in dsboxClassificationTemplate

**Comment by serbanstan** [comment]
Do you know if this happens with SVC as well?

**Comment by ckxz105** [comment]
Which SVC you mean here? @serbanstan

**Comment by proska** [comment]
Are we planning to remove SVC from the templates?

**Comment by RqS** [comment]
Not relevant now. Closing. Feel free to reopen if necessary.
