### ISSUE TITLE
BBN AudioReader Bug

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#116]
See on AWS : /dsbox_efs/runs/seed-2018-07-26-02:04/
```
Namespace(configuration_file='/dsbox_efs/config/seed-41/partition-3/31_urbansound/search_config.json', cpus=10, debug=False, output_prefix=None, timeout=55)
Using configuation:
{'cpus': 10,
 'dataset_schema': '/dsbox_efs/dataset/seed_datasets_current/31_urbansound/31_urbansound_dataset/datasetDoc.json',
 'executables_root': '/dsbox_efs/runs/seed/31_urbansound/executables',
 'pipeline_logs_root': '/dsbox_efs/runs/seed/31_urbansound/pipelines',
 'problem_root': '/dsbox_efs/dataset/seed_datasets_current/31_urbansound/31_urbansound_problem',
 'problem_schema': '/dsbox_efs/dataset/seed_datasets_current/31_urbansound/31_urbansound_problem/problemDoc.json',
 'temp_storage_root': '/dsbox_efs/runs/seed/31_urbansound/supporting_files',
 'timeout': 55,
 'training_data_root': '/dsbox_efs/dataset/seed_datasets_current/31_urbansound/31_urbansound_dataset',
 'user_problems_root': '/dsbox_efs/runs/seed/31_urbansound/user_problems'}
[INFO] No test data config found! Will split the data.
[INFO] - dsbox.controller.controller - Top level output directory: /dsbox_efs/runs/seed/31_urbansound
[INFO] Template choices:
Template ' SRI_Mean_Baseline_Template ' has been added to template base.
Template ' BBN_Audio_Classification_Template ' has been added to template base.
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] Template 0:SRI_Mean_Baseline_Template Selected. UCT:[None, None]
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it wi\
ll be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[INFO] Will use normal train-test mode ( n = 1 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.sri.baseline.MeanBaseline', 1573900334058771218)
[INFO] Testing finish.!!!
[INFO] Now in normal mode, will add extra train with train_dataset1
[INFO] Hit@cache: ('d3m.primitives.sri.baseline.MeanBaseline', 1573900334058771218)
[INFO] Now are training the pipeline with all dataset and saving the pipeline.
[INFO] Hit@cache: ('d3m.primitives.sri.baseline.MeanBaseline', 1573900334058771218)
[INFO] push@Candidate: (2191589004047544185,254f73e4-282c-485f-9734-ba5d3f565780)
[INFO] - dsbox.controller.controller - ******************
[INFO] Writing results
{'cross_validation_metrics': [],
 'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f357dfd5390>,
 'test_metrics': [{'metric': 'accuracy', 'value': 0.4868421052631579}],
 'total_runtime': 219.86583924293518,
 'training_metrics': [{'metric': 'accuracy', 'value': 0.4856512141280353}]}
[INFO] - dsbox.controller.controller - {'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f357dfd5390>, 'training_metrics': [{'metric': 'accuracy', 'value'\
: 0.4856512141280353}], 'cross_validation_metrics': [], 'test_metrics': [{'metric': 'accuracy', 'value': 0.4868421052631579}], 'total_runtime': 219.86583924293518} 0.4868421052631579
[INFO] - dsbox.controller.controller - Training accuracy = 0.4856512141280353
[INFO] - dsbox.controller.controller - Validation accuracy = 0.4868421052631579
[INFO] - dsbox.controller.controller - ******************
[INFO] Saving training results in /dsbox_efs/runs/seed/31_urbansound.txt
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] report: 0.4868421052631579
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] UCT updated: [35.28223349525836, 122.66382565317902]
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] cache size: 1, candidates: 1
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] Template 1:BBN_Audio_Classification_Template Selected. UCT:[35.28223349525836, 122.66382565317902]
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
[INFO] Will use normal train-test mode ( n = 1 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.bbn.time_series.AudioReader', 1552139140868576892)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/d3m/metadata/base.py", line 1990, in _check_selector_for_value
    element_value = for_value[segment]
  File "/usr/local/lib/python3.6/dist-packages/d3m/container/list.py", line 101, in __getitem__
    return super().__getitem__(s)
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 523, in evaluate_pipeline
    evaluation_result = self._evaluate(configuration, cache, dump2disk)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 579, in _evaluate
    fitted_pipeline.fit(cache=cache, inputs=[self.train_dataset2[each_repeat]])
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py", line 94, in fit
    self.runtime.fit(**arguments)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 195, in fit
    primitive_arguments
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 284, in _primitive_step_fit
    produce_result = model.produce(**produce_params)
  File "/src/bbn-primitives/bbn_primitives/time_series/audio_reader.py", line 140, in produce
    metadata = metadata.update((idx,), { 'sampling_rate': sampling_rate })
  File "/usr/local/lib/python3.6/dist-packages/d3m/metadata/base.py", line 928, in update
    self.check_selector(selector, for_value)
  File "/usr/local/lib/python3.6/dist-packages/d3m/metadata/base.py", line 1959, in check_selector
    cls._check_selector_for_value(selector, for_value, [])
  File "/usr/local/lib/python3.6/dist-packages/d3m/metadata/base.py", line 1992, in _check_selector_for_value
    raise ValueError("'{segment}' at {path} cannot be resolved.".format(segment=segment, path=path)) from error
ValueError: '1614' at [] cannot be resolved.
[INFO] push@Candidate: (5215552714239236152,None)
Traceback (most recent call last):
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 378, in setup_initial_candidate
    candidate.data.update(result)
TypeError: 'NoneType' object is not iterable
```

**Comment by liangmuxin** [comment]
I looked into that code , it seems that they do not update metadata correctly

-> try:
(Pdb) list
1984                        # Fetch a row as a list.
1985                        element_value = [for_value.iloc[segment, k] for k in range(len(for_value.columns))]
1986                    except Exception as error:
1987                        raise ValueError("'{segment}' at {path} cannot be resolved.".format(segment=segment, path=path)) from error
1988                else:
1989 ->                 try:
1990                        element_value = for_value[segment]
1991                    except Exception as error:
1992                        raise ValueError("'{segment}' at {path} cannot be resolved.".format(segment=segment, path=path)) from error
1993
1994                cls._check_selector_for_value(selector_rest, element_value, path + [segment])
(Pdb) for_valaue[segment]
*** NameError: name 'for_valaue' is not defined
(Pdb) for_value[segment]
*** IndexError: list index out of range
(Pdb) for_value
[ndarray([ 0.000000e+00,  0.000000e+00, -4.920049e-05, ..., -4.920049e-05,
          0.000000e+00,  0.000000e+00], dtype=float32)]
(Pdb) segment
9
(Pdb) len(for_value)
1
(Pdb) for_value[9]
*** IndexError: list index out of range
(Pdb) where
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/ta2-search(173)<module>()
-> result = main(args)
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/ta2-search(102)main()
-> status = controller.train()
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/controller/controller.py(622)train()
-> cache_bundle=(cache, candidate_cache),
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/controller/controller.py(421)search_template()
-> report = search.search_one_iter(candidate_in=candidate, cache_bundle=cache_bundle)
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(193)search_one_iter()
-> self.setup_initial_candidate(candidate_in, cache, candidate_cache)
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(374)setup_initial_candidate()
-> result = self.evaluate((candidate, cache, True if cand_tmp is None else False))
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(523)evaluate_pipeline()
-> evaluation_result = self._evaluate(configuration, cache, dump2disk)
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(579)_evaluate()
-> fitted_pipeline.fit(cache=cache, inputs=[self.train_dataset2[each_repeat]])
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py(94)fit()
-> self.runtime.fit(**arguments)
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/runtime.py(195)fit()
-> primitive_arguments
  /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/runtime.py(286)_primitive_step_fit()
-> produce_result = model.produce(**produce_params)
  /src/bbn-primitives/bbn_primitives/time_series/audio_reader.py(140)produce()
-> metadata = metadata.update((idx,), { 'sampling_rate': sampling_rate })
  /usr/local/lib/python3.6/dist-packages/d3m/metadata/base.py(928)update()
-> self.check_selector(selector, for_value)
  /usr/local/lib/python3.6/dist-packages/d3m/metadata/base.py(1959)check_selector()
-> cls._check_selector_for_value(selector, for_value, [])
> /usr/local/lib/python3.6/dist-packages/d3m/metadata/base.py(1989)_check_selector_for_value()

**Comment by liangmuxin** [comment]
Need improve our split maybe, when removing split the error fixed. Now I added "audio" to cannot split list
