### ISSUE TITLE
LL0_acled Dataset, All pipelines fail

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#119]
All pipelines fail
See /dsbox_efs/runs/seed-2018-07-26-02:04/LL0_acled/supporting_files/logs/out.txt

Should not use SKImputer?

**Comment by liangmuxin** [comment]
the SKimputer tried to impute column "event_date“ and failed to convert string to float (it is actually converting sth like '16 March 2018'). The "event_date" column, as described in datasetDoc has a datetime datatype, probably we should process that in our date_featurizer.

**Comment by liangmuxin** [comment]
Classifier also failing because of string columns

**Comment by RqS** [comment]
Fixed in latest dsbox-cleaning
