### ISSUE TITLE
SKARDRegression very slow on LL0_562_cpu_small dataset

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#126]
Took two hours to generate one pipeline using all the cores of dsbox01

**Comment by serbanstan** [comment]
It seems that this is the case on many datasets. From the experiments I've performed, ARD was the worst at actually running in the default time limit. As ExtraTrees, RandomForest etc. seem to have a similar performance, I suggest we drop ARD from our search base.
