### ISSUE TITLE
Good things to have

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#13]
Posting this here, feel free to move 

Before the system becomes too complex, it would be great to be able to have the following:
- global random seed
- being able to get training + test results for each primitive per template (maybe through a flag)

**Comment by kyao** [comment]
The 29 june 2018 commit by @ckxz105 to the `template-2018-june` branch modified the config file to include training and test during search. We actually need to refactor this functionality as not to interfere with evaluation.

**Comment by RqS** [comment]
Done
