### ISSUE TITLE
Datasets with large number of columns

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#131]
Do not split these datasets. Metadata recomputation takes too long.

For example, splitting LL0_1122_ap_breast_prostate does not finish in one hour

**Comment by kyao** [comment]
Problem datasets and their column count:

LL0_1122_ap_breast_prostate has 10938 columns
LL0_1176_internet_advertisements has 1560 columns
LL0_1457_amazon_commerce has 10002  columns
LL0_1515_micro_mass has 1302 columns
LL0_4134_bioresponse has 1778 columns

**Comment by RqS** [comment]
Implemented method that drop column for datasets with large number of columns
