### ISSUE TITLE
Cleaning Featurizer and Corex

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#133]
Cleaning Featurizer may split text fields into multiple columns. See 32_wikia dataset.

Need to add noop for Cleaning Featurizer.

**Comment by kyao** [comment]
Will add noop primitive

**Comment by RqS** [comment]
Now, Cleaning Featurizer will calculate the avg length of chars of some sampled rows. Only split on column with avg length less than some arbitrary number. Right now is 30 chars.

Noop added
