### ISSUE TITLE
Adding priority to our different detectors in cleaningfeaterizer

### ISSUE THREAD

**Issue by proska** [usc-isi-i2/dsbox-ta2#136]
The idea is date and phone parser should have higher priority compared to punctuation separator. This feature is especially important for date attributes that will definitely be detected by punction separator as well.

**Comment by szeke** [comment]
Agreed, we are doing a run with the current code, and will tackle this problem next

**Comment by RqS** [comment]
Now running date first, then phone. punction and alphanumeric will ignore the list processed by date and phone
