### ISSUE TITLE
UCT Scores #1

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#140]
Right now our UCT scores are initialized as an array of `None`. 

If we want to list templates by importance in libary.py, shouldn't we have these scores initialized to an array of positive elements in decreasing order?

**Comment by proska** [comment]
The templates are first scanned based on their order in the `self.template`, not the uct_score (as uct is invalid before this scan phase). So in order to prioritize the templates just push them first to the list. You can do it in the library.py as we add the templates to template list.
