### ISSUE TITLE
UCT Scores #2

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#141]
Final UCT scores for initial template choices

```UCT updated: [172.53055776266274, 34.507190538511, 36.457931491280355, 41.22284810596329, 35.7633862871371, 152.77268304809058, 66.47800539020673]```

```
Template ' SRI_Mean_Baseline_Template ' has been added to template base.
Template ' random_forest_classification_template ' has been added to template base.
Template ' extra_trees_classification_template ' has been added to template base.
Template ' gradient_boosting_classification_template ' has been added to template base.
Template ' naive_bayes_classification_template ' has been added to template base.
Template ' Default_timeseries_collection_template ' has been added to template base.
Template ' dsbox_classification_template ' has been added to template base.
```

Is this correct? Ran on 38 sick without a timeout.

**Comment by proska** [comment]
I do not understand the question. Are you asking about the correctness of the values or sth else?

**Comment by serbanstan** [comment]
We have the highest scores associated to the templates that perform the worst (SRI & TimeSeries). 

I'm asking if high score = template we want to sample more or the opposite. If it's the former, we have a bug.

**Comment by proska** [comment]
We use the UCT score as sampling weight. So the highest UCT score means a higher chance of being selected for next round of evaluation.
