### ISSUE TITLE
Assigning text templates to datasets

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#144]
Want the text templates to be properly assigned to datasets. Right now, they are either only called on datasets that have only "text" as task type. We want to call them on datasets that have both "text" and "tabular", but not called on datasets that have "tabular"

Some datasets that should definitely be covered by text templates:

30_personnae
32_wikiqa
LL1_airline_twitter_sentiment

Datasets that shouldn't be covered

38_sick

**Comment by liangmuxin** [comment]
Has that function been added?

**Comment by RqS** [comment]
Done
