### ISSUE TITLE
Top 20 pipelines

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#145]
For a pipeline ranked within the current top 20, save and pickle as we are doing right now.

Pipelines ranked lower than 20, save only its json description in the output/pipelines_considered directory.

**Comment by proska** [comment]
we keep a record of all processed pipelines in the candidate's cache. So we can easily get the best 20 there and re-evaluate them (which should not take long as the primitives are already in the primitive's cache).

**Comment by proska** [comment]
@kyao Please let me know if anyone is working on it
