### ISSUE TITLE
IQR Scaler breaks pipelines

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#151]
IQR Scaler seems to break with our general template system.

Until fixed, use `d3m.primitives.sklearn_wrap.SKMaxAbsScaler`

**Comment by kyao** [comment]
I checked in a fix. Please, test it.

**Comment by liangmuxin** [comment]
I am guessing this can be created by IQR Scaler？ ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by RqS** [comment]
This is fixed but not got included in latest JPL image. Will not have the fix in ta2 eval
