### ISSUE TITLE
Saving Location

### ISSUE THREAD

**Issue by liangmuxin** [usc-isi-i2/dsbox-ta2#152]
The saving location of pipelines and executables are not consistent with config file
For example:
`
{'cpus': '10',
 'dataset_schema': '/muxin/data/38_sick/TRAIN/dataset_TRAIN/datasetDoc.json',
 'executables_root': '/muxin/results/38_exec',
 'pipeline_logs_root': '/muxin/results/38_pipeline',
 'problem_root': '/muxin/data/38_sick/TRAIN/problem_TRAIN',
 'problem_schema': '/muxin/data/38_sick/TRAIN/problem_TRAIN/problemDoc.json',
 'ram': '10Gi',
 'saved_pipeline_ID': '',
 'saving_folder_loc': '/muxin/results/38_saving',
 'temp_storage_root': '/muxin/results/38_temp',
 'timeout': 499,
 'train_data_schema': '/muxin/data/38_sick/TRAIN/dataset_TRAIN/datasetDoc.json',
 'training_data_root': '/muxin/data/38_sick/TRAIN/dataset_TRAIN'}
`
It should be saving under /muxin/results/38_pipeline but it is now somehow saving under  '/muxin/results/pipelines'

**Comment by kyao** [comment]
That is an old config file format. 

Use the train and test config files generated by: https://github.com/usc-isi-i2/dsbox-experimentation/blob/master/script/generate-summer-2018-configs.py
