### ISSUE TITLE
model.fit() times out in CV code on some datasets - input and output shapes differ

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#159]
This issue might possibly affect several datasets. 

On LL0_uci_facebook_metrics_config the model.fit() step in cross_validation times out. This is line 360 in `runtime.py`. This is a problem, as this particular dataset is small.

It turns out that the dimensions of `validation_train['inputs']` and `validation_train['outputs']` differ. The former is a 360x45 matrix, the later is a 720 length array (I assume its length should be 360). 

To reproduce the error, just run our current version of the system with `python ta2-search /nas/home/stan/dsbox/runs2/config-ll0/LL0_uci_facebook_metrics_config.json 
`

**Comment by kyao** [comment]
The problem with this dataset is that it has two suggested target columns. That is why you are seeing twice the number of entries.

**Comment by kyao** [comment]
A way to get around this problem is not use ExtractColumnsBySemanticTypes to extract the target, instead use the problemDoc.json spec to determine the column.

**Comment by RqS** [comment]
Switched to use ExtractColumnsBySemanticTypes for extracting targets. Closing.
