### ISSUE TITLE
Encoder very slow on LL0_1501_semeion

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#160]
Some information:

- the dataset grows from (1274, 256) to (1274, 768) after Encoder is called
- this seems to slow down the rest of the pipelines as well

**Comment by kyao** [comment]
Added check to runtime. If after encoding the number of columns is greater than 500, raise an exception.

https://github.com/usc-isi-i2/dsbox-ta2/commit/0fef1fad28ee5107bd5c087bf9eb2838845bbb46

**Comment by RqS** [comment]
Fixed
