### ISSUE TITLE
Record ".txt"

### ISSUE THREAD

**Issue by liangmuxin** [usc-isi-i2/dsbox-ta2#167]
if all templates not finished, it wont be wrote.
We should writing this file on upper level, or discard it

**Comment by kyao** [comment]
I will add a temporary fix by writing the writing the data out more often.

**Comment by kyao** [comment]
We are already writing out the file after each template. So, we should be seeing more .txt files.

**Comment by RqS** [comment]
Do not need txt anymore. Looking at pipelines dir for report now
