### ISSUE TITLE
Encoder error - Exception: Total column limit exceeded after encoding

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#171]
On `LL0_1457_amazon_commerce_reviews` we are able to execute only a single pipeline. The dataset is large, numeric

1500 rows
10000 columns

dataset link: /nfs1/dsbox-repo/data/datasets/training_datasets/LL0/LL0_1457_amazon_commerce_reviews/LL0_1457_amazon_commerce_reviews_dataset/tables

error log: /dsbox_efs/runs/0807-run2/ll0/LL0_1457_amazon_commerce_reviews/supporting_files/logs/out.txt

**Later Edit:**

More datasets affected:
- /dsbox_efs/runs/0807-run2/ll0/LL0_298_coil2000/supporting_files/logs/out.txt
- /dsbox_efs/runs/0807-run2/ll0/LL0_1468_cnae_9/supporting_files/logs/out.txt
- /dsbox_efs/runs/0807-run2/ll0/LL0_1515_micro_mass/supporting_files/logs/out.txt

**Comment by kyao** [comment]
That column limit exceed exception is the correct behavior. Otherwise the system will freeze due to the large number of columns.

**Comment by serbanstan** [comment]
Added DoNothing alongside Encoder. More pipelines seem to be generated now.
