### ISSUE TITLE
Recent run BUG

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/dsbox-ta2#181]
In recent run for seed. Some problem failed. They have an empty /pipelines and /executables dir, but /supporting_files dir is not empty which contains pipeline_id dir, but inside is still empty.
Eg. `/dsbox_efs/runs/0809-run/seed/56_sunspots`

This run is under evaluation mode, we don not have a log now. But running locally with the problematic dataset should produce the same error.

This must be introduced by today's change.

**Comment by liangmuxin** [comment]
I am guess the reason of failure is that those dataset does not have tasksubtype

**Comment by liangmuxin** [comment]
pushed a fix
