### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by proska** [usc-isi-i2/dsbox-ta2#19]
The "ta2-search.py" code does not run in the current  #17 . In 'Controller.py':8 we have `import dsbox.template.runtime as runtime` that results in following error:  
ModuleNotFoundError: No module named 'dsbox.template.runtime'.

In the previous version of the code, this line was `import d3m.runtime as runtime`. So either the file is not added to repo or this import should not change.

**Comment by kyao** [comment]
Just added runtime.py

For now I decided to move runtime.py into our code, so the people don't have to manually copy my version of the file. If d3m updates their runtime.py, then we may switch back.
