### ISSUE TITLE
Training_Ground_truth was changed?

### ISSUE THREAD

**Issue by liangmuxin** [usc-isi-i2/dsbox-ta2#192]
[INFO] - dsbox.controller.controller - [INFO] Template 0:SRI_Mean_Baseline_Template Selected. UCT:[None, None, None]
[INFO] - dsbox.controller.controller - Searching template SRI_Mean_Baseline_Template
[INFO] - dsbox.controller.controller - cache size = 0
[INFO] Using Global Cache
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-08-17 00:45:32.240880: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[INFO] Will use normal train-test mode ( n = 1 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.sri.baseline.MeanBaseline', 7073465230505086500)
> /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(628)_evaluate()
-> training_ground_truth = get_target_columns(self.train_dataset2[each_repeat], self.problem)
(Pdb) n
> /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(629)_evaluate()
-> training_prediction = fitted_pipeline.get_fit_step_output(self.template.get_output_step_number())
(Pdb) training_ground_truth.head()
  d3mIndex classLabel
0        0          2
1        1          0
2        2          0
3        3          0
4        4          1
(Pdb) c
> /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(842)_calculate_score()
-> training_metrics = []
(Pdb) c
[INFO] Testing finish.!!!
The dataset no need to split of split failed, will not train again.
!!!! No test_dataset1
{'cross_validation_metrics': [],
 'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f93fe714828>,
 'test_metrics': [{'column_name': 'classLabel',
                   'metric': 'accuracy',
                   'value': 0.43}],
 'total_runtime': 153.62254333496094,
 'training_metrics': [{'column_name': 'classLabel',
                       'metric': 'accuracy',
                       'value': 0.43}]}
!!!!
The following pipeline file will be loaded:
/nfs1/dsbox-repo/muxin/ta2-outputs/seed/LL1_net_nomination_seed/pipelines/43bd5ee3-19b6-4dac-9b57-c80e4c9424ea.json
> /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(842)_calculate_score()
-> training_metrics = []
(Pdb) c
=== original
[{'column_name': 'classLabel', 'metric': 'accuracy', 'value': 0.43}]
=== test
[{'metric': 'accuracy', 'value': 0.43}]
=== test2
[{'column_name': 'classLabel', 'metric': 'accuracy', 'value': 0.43}]

Pickling succeeded

[INFO] push@Candidate: (6938335799200866349,43bd5ee3-19b6-4dac-9b57-c80e4c9424ea)
[INFO] - dsbox.controller.controller - ******************
[INFO] Writing results
{'cross_validation_metrics': [],
 'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f93fe714828>,
 'test_metrics': [{'column_name': 'classLabel',
                   'metric': 'accuracy',
                   'value': 0.43}],
 'total_runtime': 153.62254333496094,
 'training_metrics': [{'column_name': 'classLabel',
                       'metric': 'accuracy',
                       'value': 0.43}]}
[INFO] - dsbox.controller.controller - {'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f93fe714828>, 'training_metrics': [{'column_name': 'classLabel', 'metric': 'accuracy', 'value': 0.43}], 'cross_validation_metrics': [], 'test_metrics': [{'column_name': 'classLabel', 'metric': 'accuracy', 'value': 0.43}], 'total_runtime': 153.62254333496094} 0.43
[INFO] - dsbox.controller.controller - Training accuracy = 0.43
[INFO] - dsbox.controller.controller - Validation accuracy = 0.43
[INFO] - dsbox.controller.controller - [INFO] report: 0.43
[INFO] - dsbox.controller.controller - [INFO] UCT updated: [35.60422431326317, 125.88373383322705, 125.88373383322705]
[INFO] - dsbox.controller.controller - [INFO] cache size: 2, candidates: 1
[INFO] - dsbox.controller.controller - [INFO] New Best Value: 0.43
[INFO] - dsbox.controller.controller - ******************
[INFO] Saving training results in /nfs1/dsbox-repo/muxin/ta2-outputs/seed/LL1_net_nomination_seed.txt
[INFO] The config of the template is
{'inputType': {'edgeList', 'graph'},
 'name': 'SRI_Vertex_Nomination_Template',
 'output': 'model_step',
 'steps': [{'inputs': ['template_input'],
            'name': 'parse_step',
            'primitives': ['d3m.primitives.sri.graph.VertexNominationParser']},
           {'inputs': ['parse_step'],
            'name': 'model_step',
            'primitives': ['d3m.primitives.sri.psl.VertexNomination']}],
 'taskSubtype': 'NONE',
 'taskType': 'VERTEX_NOMINATION'}
[INFO] - dsbox.controller.controller - [INFO] Template 1:SRI_Vertex_Nomination_Template Selected. UCT:[35.60422431326317, 125.88373383322705, 125.88373383322705]
[INFO] - dsbox.controller.controller - Searching template SRI_Vertex_Nomination_Template
[INFO] - dsbox.controller.controller - cache size = 2
[INFO] Using Global Cache
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
[INFO] Will use normal train-test mode ( n = 1 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.sri.graph.VertexNominationParser', 7073465230505086500)
[INFO] Push@cache: ('d3m.primitives.sri.psl.VertexNomination', -5765124488841008253)
> /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(628)_evaluate()
-> training_ground_truth = get_target_columns(self.train_dataset2[each_repeat], self.problem)
(Pdb) n
> /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(629)_evaluate()
-> training_prediction = fitted_pipeline.get_fit_step_output(self.template.get_output_step_number())
(Pdb) training_ground_truth.head()
  d3mIndex classLabel
0        0          2
1        1          0
2        2          0
3        3          0
4        4          1
(Pdb) c
> /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(842)_calculate_score()
-> training_metrics = []
(Pdb) c
[INFO] Testing finish.!!!
The dataset no need to split of split failed, will not train again.
!!!! No test_dataset1
{'cross_validation_metrics': [],
 'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f90e5e588d0>,
 'test_metrics': [{'column_name': 'classLabel',
                   'metric': 'accuracy',
                   'value': 0.18}],
 'total_runtime': 87.31890726089478,
 'training_metrics': [{'column_name': 'classLabel',
                       'metric': 'accuracy',
                       'value': 0.18}]}
!!!!
The following pipeline file will be loaded:
/nfs1/dsbox-repo/muxin/ta2-outputs/seed/LL1_net_nomination_seed/pipelines/9e8785df-0058-4a84-8a2c-f3762d15d476.json
> /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(842)_calculate_score()
-> training_metrics = []
(Pdb) c
=== original
[{'column_name': 'classLabel', 'metric': 'accuracy', 'value': 0.18}]
=== test
[{'metric': 'accuracy', 'value': 0.18}]
=== test2
[{'column_name': 'classLabel', 'metric': 'accuracy', 'value': 0.18}]

Pickling succeeded

[INFO] push@Candidate: (7778153321987499849,9e8785df-0058-4a84-8a2c-f3762d15d476)
[INFO] - dsbox.controller.controller - ******************
[INFO] Writing results
{'cross_validation_metrics': [],
 'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f90e5e588d0>,
 'test_metrics': [{'column_name': 'classLabel',
                   'metric': 'accuracy',
                   'value': 0.18}],
 'total_runtime': 87.31890726089478,
 'training_metrics': [{'column_name': 'classLabel',
                       'metric': 'accuracy',
                       'value': 0.18}]}
[INFO] - dsbox.controller.controller - {'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f90e5e588d0>, 'training_metrics': [{'column_name': 'classLabel', 'metric': 'accuracy', 'value': 0.18}], 'cross_validation_metrics': [], 'test_metrics': [{'column_name': 'classLabel', 'metric': 'accuracy', 'value': 0.18}], 'total_runtime': 87.31890726089478} 0.18
[INFO] - dsbox.controller.controller - Training accuracy = 0.18
[INFO] - dsbox.controller.controller - Validation accuracy = 0.18
[INFO] - dsbox.controller.controller - [INFO] report: 0.18
[INFO] - dsbox.controller.controller - [INFO] UCT updated: [36.78903598153923, 136.67388860960256, 137.73185051598767]
[INFO] - dsbox.controller.controller - [INFO] cache size: 6, candidates: 2
[INFO] The config of the template is
{'inputType': 'graph',
 'name': 'JHU_Vertex_Nomination_Template',
 'output': 'model_step',
 'steps': [{'inputs': ['template_input'],
            'name': 'readgraph_step',
            'primitives': ['d3m.primitives.jhu_primitives.LargestConnectedComponent']},
           {'inputs': ['readgraph_step'],
            'name': 'embedding_step',
            'primitives': ['d3m.primitives.jhu_primitives.AdjacencySpectralEmbedding']},
           {'inputs': ['embedding_step'],
            'name': 'model_step',
            'primitives': ['d3m.primitives.jhu_primitives.GaussianClassification']}],
 'taskSubtype': 'NONE',
 'taskType': 'VERTEX_NOMINATION'}
[INFO] - dsbox.controller.controller - [INFO] Template 2:JHU_Vertex_Nomination_Template Selected. UCT:[36.78903598153923, 136.67388860960256, 137.73185051598767]
[INFO] - dsbox.controller.controller - Searching template JHU_Vertex_Nomination_Template
[INFO] - dsbox.controller.controller - cache size = 6
[INFO] Using Global Cache
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
[INFO] Will use normal train-test mode ( n = 1 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.jhu_primitives.LargestConnectedComponent', 7073465230505086500)
[INFO] Push@cache: ('d3m.primitives.jhu_primitives.AdjacencySpectralEmbedding', -4723859704814392067)
[INFO] Push@cache: ('d3m.primitives.jhu_primitives.GaussianClassification', 4184838155020800425)
> /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(628)_evaluate()
-> training_ground_truth = get_target_columns(self.train_dataset2[each_repeat], self.problem)
(Pdb) n
> /nfs1/dsbox-repo/muxin/dsbox7_10/dsbox-ta2/python/dsbox/template/search.py(629)_evaluate()
-> training_prediction = fitted_pipeline.get_fit_step_output(self.template.get_output_step_number())
(Pdb) training_ground_truth.head()
  d3mIndex  classLabel
0        0         2.0
1        1         2.0
2        2         2.0
3        3         2.0
4        4         2.0

Look at the inconsistency of training_ground_truth, anyone has idea about that?

**Comment by ckxz105** [comment]
Good question, maybe you need to help them to fix jhu's bug again

**Comment by liangmuxin** [comment]
Changing in training ground truth fixed by making deep copy for dataset, new issue:

`> /Users/muxin/Desktop/ISI/dsbox-env/dsbox-ta2/python/dsbox/template/search.py(770)_evaluate()
-> fitted_pipeline2.save(self.output_directory)
(Pdb) n
d3m.exceptions.InvalidArgumentTypeError: Value '[0.18 0.39 0.43]' for parameter 'pis' is not an instance of the type: <class 'd3m.container.numpy.ndarray'>`
