### ISSUE TITLE
unable to run the program in debug mode with pdb

### ISSUE THREAD

**Issue by ckxz105** [usc-isi-i2/dsbox-ta2#213]
Currently, due to the reason that now we use multi-processing for nearly the whole template searching, it is impossible to run debug mode with `pdb `with step by step. 
Maybe we need a debug mode that run one evaluate() function one time only but not multiprocess for debugging purpose.

**Comment by ckxz105** [comment]
I find one possible way to debug, I will put codes here if some one also need:

```
import sys
import pdb

class ForkedPdb(pdb.Pdb):
    """A Pdb subclass that may be used
    from a forked multiprocessing child

    """
    def interaction(self, *args, **kwargs):
        _stdin = sys.stdin
        try:
            sys.stdin = open('/dev/stdin')
            pdb.Pdb.interaction(self, *args, **kwargs)
        finally:
            sys.stdin = _stdin
```

After adding this class, run with 
`ForkedPdb().set_trace()` and you can enter the debugging mode

**Comment by proska** [comment]
It depends on which part of the code do you want to run pdb in:
1. for 'pipeline evaluation' only you can use 'combinatorial_search/TemplateSpaceBaseSearch.py' as search method which does not do any multiprocessing.
2. if you want to step through other aspects of search I am afraid using breakpoints is not reasonable. It is a classical challenge in multiprocessing applications.
Let me know what exactly you want to do?

**Comment by ckxz105** [comment]
Yes, that way seems works. But one thing need to notice is that we still need to use Forkedpdb instead of normal pdb from python.
