### ISSUE TITLE
new search algorithm failed on some conditions without return self.history.get_best_history()

### ISSUE THREAD

**Issue by ckxz105** [usc-isi-i2/dsbox-ta2#221]
When running the searching with _run_MultiBanditSearch and _run_ParallelBaseSearch, sometimes the program will stuck with some jobs not finished like following screenshot. (sometimes it just finished successfully)
![image](https://user-images.githubusercontent.com/25087508/48151160-69454b00-e275-11e8-939b-f4f55d899093.png)
It will take more than 10 - 20 minutes for the program to skip this ongoing job and then it seems the program will skip` return self.history.get_best_history()`. Which will influence our new system because we need to get the returned report at controller.
Any idea for this condition?

**Comment by ckxz105** [comment]
for more some details: 
(This one succeeded, we can see it reached break point and we get results)
![image](https://user-images.githubusercontent.com/25087508/48159023-065daf00-e289-11e8-980f-2f7775e55591.png)

![image](https://user-images.githubusercontent.com/25087508/48159048-14abcb00-e289-11e8-96fe-a60b55a500bf.png)
![image](https://user-images.githubusercontent.com/25087508/48159081-23927d80-e289-11e8-8c2b-2d284761d25e.png)



(This one failed, we can see it didn't reach the break point it should arrive)
![image](https://user-images.githubusercontent.com/25087508/48158907-a6670880-e288-11e8-9b5f-c50363147dea.png)

**Comment by ckxz105** [comment]
After checking the details, it seems the error happened when 

> are_queues_empty: True and True

![image](https://user-images.githubusercontent.com/25087508/49903700-edfb2a00-fe1c-11e8-85cf-65608af1d640.png)

The program stopped when I comes to `pop_job`

This problem tends to be more terrible when adding more templates into the system for searching. It should be solved **ASAP**.

**Comment by kyao** [comment]
@proska Would you please look into his problem. This distributed job manager seems quite unstable. Jobs that run fine under serial mode sometimes get stuck in distributed mode.

**Comment by proska** [comment]
I have pushed a fix for this issue. In case you still face it, please send me the log dump of your execution.

**Comment by proska** [comment]
It seems we do not have this issue anymore. I will close it for now.
