### ISSUE TITLE
Should not use cast_to_type primitive

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#233]
The primitive `d3m.primitives.data_transformation.extract_columns_by_structural_types.DataFrameCommon` removes the `d3mIndex` column. But, the `d3mIndex` column is required in the final prediction output. Before we can simply add the column back to the prediction results. But, now with the official d3m runtime we cannot do that.

**Comment by liangmuxin** [comment]
A reminder: Also we need to include PrimaryKey in ExtractAttribute primitive to keep d3mIndex
