### ISSUE TITLE
Pipeline Runtime for test datasets

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#24]
The dsbox.template.runtime.Runtime.produce() method executes all primitives of the pipeline graph. However, some steps should not be ran for test datasets, i.e. datasets without target column. The ExtractTargets -> CastToType2 part of the pipeline would failed. Need a way to inform Runtime to skip those primitives.

**Comment by kyao** [comment]
Our current Runtime is copied from the d3m repo runtime branch. They are planning to update it. We need to track their changes.

**Comment by kyao** [comment]
The latest runtime.py from the d3m runtime branch is supposed to fix this.

**Comment by RqS** [comment]
Not relevant anymore
