### ISSUE TITLE
Some primitive names are misspecified ?

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#245]
When running on 38_sick:

> 02-28 14:49:56 [INFO] dsbox.JobManager.DistributedJobManager -- # ongoing_jobs 17
> # ongoing_jobs 17
> <ForkProcess(ForkPoolWorker-8, started daemon)> > Target evaluation failed 1902284355320786904
> Traceback (most recent call last):
>   File "/nfs1/dsbox-repo/stan/dsbox-1020/dsbox-ta2/python/dsbox/JobManager/DistributedJobManager.py", line 109, in _internal_worker_process
>     result = target(**kwargs)
>   File "/nfs1/dsbox-repo/stan/dsbox-1020/dsbox-ta2/python/dsbox/JobManager/DistributedJobManager.py", line 75, in _posted_job_wrapper
>     result = method_to_call(**kwargs)
>   File "/nfs1/dsbox-repo/stan/dsbox-1020/dsbox-ta2/python/dsbox/combinatorial_search/ConfigurationSpaceBaseSearch.py", line 187, in evaluate_pipeline
>     evaluation_result = self._evaluate(configuration, cache, dump2disk)
>   File "/nfs1/dsbox-repo/stan/dsbox-1020/dsbox-ta2/python/dsbox/combinatorial_search/ConfigurationSpaceBaseSearch.py", line 210, in _evaluate
>     pipeline = self.template.to_pipeline(configuration)
>   File "/nfs1/dsbox-repo/stan/dsbox-1020/dsbox-ta2/python/dsbox/template/template.py", line 428, in to_pipeline
>     binding, sequence = self.add_intermediate_type_casting(ioconf)
>   File "/nfs1/dsbox-repo/stan/dsbox-1020/dsbox-ta2/python/dsbox/template/template.py", line 472, in add_intermediate_type_casting
>     in_primitive_value = d3m_index.get_primitive(binding[name]["primitive"]).metadata.query()[
>   File "/nfs1/dsbox-repo/stan/dsbox-1020/d3m/d3m/index.py", line 115, in get_primitive
>     module = importlib.import_module(path)
>   File "/nas/home/stan/nfs1-stan/miniconda3/envs/dsbox-devel-201902/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'd3m.primitives.data_preprocessing.select_fwe'

**Comment by liangmuxin** [comment]
fixed in new release
