### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#30]
Need to update our TA2 output to better conform to the evaluation spec. Currently, we are storing our primitive pickle files in directories under `executables`. These directories should be moved to `supporting_files` directory. According to the evaluation spec, there should only be files in `executables`.  Each file in `executables` specifies a specific pipeline generated by our system. The evaluation system will give this file to our TA2 system as argument.

The proposal is to have our pipeline spec under `executables` to be a json file. This json file simply specifies the pipeline id. 
```
{
    "fitted_pipeline_id" : "2a61ba42-e08b-47cc-a0bb-40cec7c1f3a7"
}
```

With this `executable/<pipeline_id>.json`, our ta2 system can walk up the `supporting_files\<pipeline_id>` directory to load the pickle files, and look up the pipeline definition in `pipelines\<pipeline_id>.json`

Here is the directory hierarchy from the evaluation spec:
```
./pipelines
    <pipelineId_1>.json
./executables
    <pipelineId_1>.yyy
./supporting_files
    ./<pipelineId_1>
        file1.yyy
        file2.yyy
        ./folder1
./predictions
    ./<pipelineId_1>
        predictions.csv
metadata.yml
```

**Comment by RqS** [comment]
@kyao Finished and got merged into branch 'template-2018-june' with commit 86e890fbd1815c76e2e222c23be8ac0b72c34ccd, please check

**Comment by kyao** [comment]
@RqS Looks good to me
