### ISSUE TITLE
Pipeline verus Fitted Pipeline

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#36]
In our system the distinction between pipeline and fitted pipeline is not clearly maintained.

A pipeline, i.e. d3m.metadata.pipeline.Pipeline, is just a graph where each node is associated with a python path to a primitive. it does not have actual instantiated primitives associated with it. A Runtime object is used to hold the instantiated primitives, and to perform pipeline-level fit() and produce() operations.

A fitted pipeline can be considered as a pipeline with instantiated primitives. A fitted pipeline is associated with exactly one pipeline, one runtime, and one dataset.

A pipeline may have more than one associated fitted pipelines, since a pipeline may be ran with different datasets. A fitted pipeline should id distinct from its pipeline and from other fitted pipelines.

Clearly, maintaining this distinction would also conform with TA2TA3 API semantics.

In our system we do have a class called FittedPipeline, but it is only used for saving and loading. The proposal is to use this FittedPipeline class, where ever the notion of fitted pipeline is need. 

This change would require changing at least controller.py, search.py and fitted_pipeline.py.

**Comment by proska** [comment]
fixed in latest "template-2018-june" verison.
