### ISSUE TITLE
Integrate Profiler and CleaningFeaturizer to default templates

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/dsbox-ta2#41]

**Comment by RqS** [comment]
@kyao Profiler and CleaningFeaturizer can be added to template and work. However, if I add Encoder after CleaningFeaturizer, it is producing some error. It would be good if you can take a look. 
Column folder is not doing well. Need to talk next week.

**Comment by kyao** [comment]
Okay, let's talk on monday

**Comment by RqS** [comment]
TA1Classification_3 template has Profiler and CleaningFeaturizer integrated.
