### ISSUE TITLE
Track runtime for each pipeline

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#42]
It would be nice to know how long each pipeline takes to run. This would be helpful for keeping track of cost/reward for specific hyperparameter choices.

**Comment by proska** [comment]
Would you add it yourself? You just need to change the _evaluation method to time itself and store the result in the data variable it the end.
`data = {
            'fitted_pipeline': fitted_pipeline,
            'training_metrics': training_metrics,
            'validation_metrics': validation_metrics
        }`

**Comment by serbanstan** [comment]
Now implemented.
