### ISSUE TITLE
Problem with controller.write_training_results when run ta2-seatch with latest change

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/dsbox-ta2#46]
https://github.com/usc-isi-i2/dsbox-ta2/blob/3991914855c34082748db01bbe049057fe799d4d/python/ta2-search#L48

https://github.com/usc-isi-i2/dsbox-ta2/blob/3991914855c34082748db01bbe049057fe799d4d/python/dsbox/controller/controller.py#L230

**Comment by kyao** [comment]
What errors are you getting? stacktrace?

**Comment by RqS** [comment]
It just stucks. Seems like more than one problem

**Comment by kyao** [comment]
Which problems got stuck?

**Comment by RqS** [comment]
Im running with LL0_188

**Comment by kyao** [comment]
Looks like the write_training_results() methods is not normally called. That is a separate bug we have to fix.

Right now write_training_results() is called only when you press control-c and try to interrupt the process. The slowness must be coming from somewhere else. 

Can you try commenting out the signal handler registration part of the code in ta2-search, and test again.  This comment out the `if timeout > 0` statement start at line 69.

**Comment by proska** [comment]
Do we need this method at all? Right now we store each pipeline after evaluation so there is nothing else to write after the search. 
The "write_training_results" was written based on previous pipeline/runtime format, not the fitted_pipline that we currently use.  If we still need it then we must rewrite the method

**Comment by RqS** [comment]
@kyao @proska Still need fixed or not? I saw we return None anyway.
https://github.com/usc-isi-i2/dsbox-ta2/blob/ef43fc871ecc65606887f904eb7e95c115072f22/python/dsbox/controller/controller.py#L301

**Comment by kyao** [comment]
There is nothing to fix. We are writing the fitted_pipelines as they are generated.
