### ISSUE TITLE
Update UnaryEncoder

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#52]
Update UndaryEncoder to conform to the new API by using column semantic types.

This should be an issue in dsbox-cleaning repo, but added here to centralize all issues.

**Comment by ckxz105** [comment]
fitted after this version
https://github.com/usc-isi-i2/dsbox-cleaning/commit/7a6f847c19a0e442e351e6cb0e8d99038a0bc1e5
