### ISSUE TITLE
Update MultiTableFeaturization

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#53]
Need to think about how this featurizer fit into the current framework.

This issues belongs to the dsbox-featurization repo, but added here to centralize all issues.

**Comment by ckxz105** [comment]
Fixed temporally on found data type (only backward direction fixed, the forward direction not fixed) after https://github.com/usc-isi-i2/dsbox-featurizer/commit/5d80c3f75787b39850752c90831e11a4c5093112
