### ISSUE TITLE
Denormalize takes extremely long on some datasets

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#57]
Running 

python ta2-search /nas/home/stan/dsbox/runs2/config-seed/32_wikiqa_config.json

doesn't get passed the denormalize step in 30 minutes.

**Comment by ckxz105** [comment]
solved on our own primitives after https://github.com/usc-isi-i2/dsbox-cleaning/commit/b3c725d16dfba1888c481353b366616dc133e767#diff-6181b424faea596dae3496597dd8b8b6
