### ISSUE TITLE
can't find templates for 30_personae

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#61]
~~EDIT: There are two issues with this dataset. First, the system is not able to find a suitable template. Second, after forcing the system to use a template, column parser breaks.~~

~~It might seem that the first issue makes the second invalid, but I remember running the system on this dataset a couple of weeks ago, and after selecting a classification template I had no other issues. The tracekback is here **https://pastebin.com/WfpBmum4**~~
 
------------------------------------------------------------------------------

My proposed fix requires changing

`if taskSourceType == {"table"} and template.template['inputType'] == "table":`

to

`if "table" in taskSourceType and template.template['inputType'] == "table":`

in library.py, get_templates. 

The reason we are currently not finding any templates is because `taskSourceType = {"text", "table"}`, and our system is only looking for "table".

**Comment by RqS** [comment]
@serbanstan Is this working now?

**Comment by serbanstan** [comment]
Fixed, closing issue.
