### ISSUE TITLE
Should not use testing set to select primitives

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#72]
Currently, we are using the testing set at each step of the dimensional search process to pick the best primitive. This will bias our search process toward the testing set and overfit.

To make it totally unbiased toward the testing set, we should only use the testing set for the final ranking of pipelines. 

This would mean that for each step of the dimensional search we would have to have some other way of picking the best primitive. If we use k-fold cross-validation and there n primitives to select from, then computational complexity would increase from n to k*n. Or, if we further split training set into two (one to use for training and the other for selecting), then computational complexity remains n.

A compromise would be to do k-fold cross-validation for "important" steps, and splitting for the rest of the steps.

**Comment by ckxz105** [comment]
fixed after https://github.com/usc-isi-i2/dsbox-ta2/commit/21ba905752dcaf1f3a8eb26fa68af5e2c1124f54
