### ISSUE TITLE
TA2 Scripts for Evaluation

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#73]
We need script(s) to submit along with our TA2 system for evaluation.

The script(s) should do:

- Run our TA2 system to generate fitted pipelines (search mode)
- Run a fitted pipeline (test mode)
- Run our TA2 system in server mode (TA3 mode)

We have to modify this sample d3mStart.sh file to call our script(s):
https://gitlab.datadrivendiscovery.org/d3m/d3m-summer2018-run-example/blob/master/d3mStart.sh

Our script(s) should look up shell environment variables for number of CPUs, RAM and Timout. See this sample Kubernetes script that set these environment variables:
https://gitlab.datadrivendiscovery.org/d3m/d3m-summer2018-run-example/blob/master/example.yaml

In search mode the config file will always be at /input/search_config.json
In test mode the config will always be at /input/test_config.json
TA3 mode does not require config files

**Comment by kyao** [comment]
Also, here is the ta2 jump server account for testing the scripts

ssh ta2-isi@k8s.datadrivendiscovery.org -i ~/.ssh/dsbox_rsa

**Comment by RqS** [comment]
Tested on jump server, it works. Done
