### ISSUE TITLE
TA2: Sample dataset instead of using the entire dataset

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#89]

**Comment by proska** [comment]
A good approach would be to use a method inspired by robust regression methods like RANSAC. In those methods, the ML model first samples a relatively small subset from the training set, then trains on the subset and then evaluate the method on the rest of the data. Then the model repeats this process until it gets a model that generalizes well on the rest of the training set. 
The way we can implement this behavior is to use our CV method with a large evaluation set (maybe 80% of the training data).

**Comment by kyao** [comment]
Does this approach work for classification problems as well?

**Comment by proska** [comment]
The assumption is the model trained on a small subset of data points can generalize on the whole dataset. There are two extra implicit assumptions as well: 
1. the classification model can converge on the small subset (e.g. in case of linear classifier three data points are theoretically enough for uniquely converge to the line)
2. Realisability assumption, meaning there is a model in the hypothesis space that fits the data (i have not seen this in the literature and I have not checked the proofs but based on what I have seen we should have it).

So overall, if I want to give a simple answer to your question is for large datasets if the training set (the subset that we use for training) is large enough, then yes we can use this for classification as well. However to compensate for not using the whole dataset we can increase the number of times we repeat this sampling-evaluation process.

**Comment by proska** [comment]
Any progress on this?

**Comment by kyao** [comment]
Need someone to work on this issue

**Comment by RqS** [comment]
@ckxz105 have implemented this
