### ISSUE TITLE
Try UnseenLabelEncoderPrimitive

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#91]
This primitive should be more robust then our Labeler

**Comment by proska** [comment]
Who is working on adding this to all the templates?

**Comment by liangmuxin** [comment]
Where is it?

**Comment by kyao** [comment]
It's here https://gitlab.com/datadrivendiscovery/common-primitives/tree/master/common_primitives

**Comment by liangmuxin** [comment]
It is pretty slow, reported to JPL
