### ISSUE TITLE
Datasets with large gap between training and testing

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#93]
From AWS run
output dir: /dsbox_efs/runs/ll0--2018-07-19-20:00

=== LL0_1530_volcanoes_a4.txt
[{'metric': <PerformanceMetric.F1_MACRO: 6>, 'params': {}}]
0.9323586367446854
0.36253968253968255
=== LL0_1549_autouniv_au6_750.txt
[{'metric': <PerformanceMetric.F1_MACRO: 6>, 'params': {}}]
0.994211164107919
0.1653166979792367
=== LL0_1554_autouniv_au7_500.txt
[{'metric': <PerformanceMetric.F1_MACRO: 6>, 'params': {}}]
0.9760168291494701
0.3655080721747388
=== LL0_475_analcatdata_germangss.txt
[{'metric': <PerformanceMetric.F1_MACRO: 6>, 'params': {}}]
0.8378520361040116
0.0960960960960961

**Comment by proska** [comment]
How can I see their testing set results?
